# -*- coding: utf-8 -*-
"""SMB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlHV8zHI5rKuJnOg9VgSA9FHJ8ByfUNp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/SMB_Port_Dynamic_Line.csv')
print("Data loaded successfully!")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

print("\n--- EDA: Exploring Credit Risk Data ---")

print("\n1. Credit Risk Concept and Calculation:")
print("Credit risk is the possibility of a borrower failing to repay a loan or meet their debt obligations.")
print("Credit risk assessment evaluates factors like credit history, income, loan terms, and collateral.")
print("Key metrics:")
print("- Probability of Default (PD%): The likelihood that a borrower will default on their debt.")
print("- Net Credit Loss (NCL%): The total amount the lender is at risk for at the time of default.")

print("\n2. Exploring the Credit Data:")
print("\nFirst 5 rows:")
print(df.head())

print("\nDataframe information:")
df.info()

print("\nSummary statistics of numerical features:")
print(df.describe())

print("\nValue counts of categorical features:")
for column in df.select_dtypes(include='object').columns:
    print(f"\nValue counts for column '{column}':")
    print(df[column].value_counts())

print("\n3. Correlation Heatmap with Target Variable DynamicCreditLine:")
print("\nTo simplify the analysis, we generate a heatmap showing correlation of all numerical variables with the target variable.")

numerical_df = df.select_dtypes(include=np.number).copy()

correlation_with_target = numerical_df.corr()['DynamicCreditLine'].sort_values(ascending=False)

print("\nCorrelation Table with DynamicCreditLine:")
print(correlation_with_target.to_frame())

plt.figure(figsize=(8, 10))
sns.heatmap(correlation_with_target.to_frame(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation with DynamicCreditLine')
plt.show()

print("\n4. Outliers in Credit Data:")
print("Outliers are data points that significantly deviate from the rest of the data.")
print("They can skew statistical analyses and affect machine learning model performance.")

print("\n5. Value Frequency of Binary Columns:")
for column in df.columns:
    if df[column].nunique() == 2:
        print(f"\nValue counts for binary column '{column}':")
        print(df[column].value_counts())

print("\nExamining Distributions with Histograms and KDE Plots:")
for column in numerical_df.columns:
    if numerical_df[column].nunique() > 2:
        plt.figure(figsize=(8, 6))
        sns.histplot(numerical_df[column], kde=True)
        plt.title(f'Distribution of {column}')
        plt.show()
    else:
        print(f"\nSkipping histogram for '{column}' as it is binary.")

print("\n6. Identifying Outliers using IQR Method (Non-Binary Columns):")
for column in numerical_df.columns:
    if numerical_df[column].nunique() > 2:
        Q1 = numerical_df[column].quantile(0.25)
        Q3 = numerical_df[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers_iqr = numerical_df[column][(numerical_df[column] < lower_bound) | (numerical_df[column] > upper_bound)]
        if not outliers_iqr.empty:
            print(f"\nPotential outliers in '{column}' (IQR method):")
            print(outliers_iqr.head())
        else:
            print(f"\nNo significant outliers found in '{column}' using IQR method.")
    else:
        print(f"\nSkipping IQR outlier detection for binary column '{column}'.")

print("\n7. Removing Outliers (IQR Method, Non-Binary Columns):")
original_row_count = len(df)
rows_removed_per_column = {}
df_cleaned = df.copy()

for column in numerical_df.columns:
    if numerical_df[column].nunique() > 2:
        Q1 = df_cleaned[column].quantile(0.25)
        Q3 = df_cleaned[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers_mask = (df_cleaned[column] < lower_bound) | (df_cleaned[column] > upper_bound)
        rows_removed = outliers_mask.sum()

        if rows_removed > 0:
            df_cleaned = df_cleaned[~outliers_mask]
            rows_removed_per_column[column] = rows_removed
            print(f"\nRemoved {rows_removed} rows with IQR outliers in column '{column}'.")
        else:
            print(f"\nNo IQR outliers found in column '{column}'.")
    else:
        print(f"\nSkipping outlier removal for binary column '{column}'.")

print(f"\n--- Summary of Rows Removed ---")
print(f"Original number of rows: {original_row_count}")
print(f"Number of rows after outlier removal: {len(df_cleaned)}")
print(f"Total number of rows removed: {original_row_count - len(df_cleaned)}")
print("\nRows removed per column (if any):")
for column, count in rows_removed_per_column.items():
    print(f"- '{column}': {count}")

print("\nCleaned DataFrame (first 5 rows):")
print(df_cleaned.head())

print("\n8. Risk with Missing Data in Loan Data:")
print("Missing data is a common problem in real-world datasets.")
print("Missing values in crucial features like income or credit score can significantly impact credit risk assessment.")

print("\n9. Replacing Missing Credit Data:")
print("Techniques: Imputation with mean, median, mode, or a special category value.")

print("\nLet's check for missing values:")
print(df.isnull().sum().sort_values(ascending=False))

print("\n10. Split data into Train, Validation, and Test Data:")
train_df, temp_df = train_test_split(df_cleaned, test_size=0.3, random_state=42)
val_df, test_df   = train_test_split(temp_df, test_size=0.5, random_state=42)

print(f"Training data shape: {train_df.shape}")
print(f"Validation data shape: {val_df.shape}")
print(f"Test data shape: {test_df.shape}")

# Impute missing Collateral_Type with 'Unknown'
train_df['Collateral_Type'] = train_df['Collateral_Type'].fillna('Unknown')
val_df['Collateral_Type']   = val_df['Collateral_Type'].fillna('Unknown')
test_df['Collateral_Type']  = test_df['Collateral_Type'].fillna('Unknown')

print("\nMissing Collateral_Type values after imputation:")
print(f"Training: {train_df['Collateral_Type'].isnull().sum()}")
print(f"Validation: {val_df['Collateral_Type'].isnull().sum()}")
print(f"Test: {test_df['Collateral_Type'].isnull().sum()}")

print("\nDynamicCreditLine distribution in Train Data:")
print(train_df['DynamicCreditLine'].describe())

industry_credit_stats = (
    df_cleaned.groupby('Industry_Type')['DynamicCreditLine']
    .agg(['count', 'mean', 'median', 'min', 'max'])
    .sort_values(by='mean', ascending=True)
)

print("\n--- Average Credit Line by Industry Type ---")
print(industry_credit_stats)

plt.figure(figsize=(12, 6))
sns.barplot(data=industry_credit_stats.reset_index(), x='Industry_Type', y='mean', palette='viridis')
plt.xticks(rotation=45, ha='right')
plt.ylabel('Average Dynamic Credit Line')
plt.xlabel('Industry Type')
plt.title('Average Dynamic Credit Line by Industry Type')
plt.tight_layout()
plt.show()

"""Feature Engineering + XGBoost Classification"""

from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
from xgboost import XGBClassifier

# Create target variable: AdjustCreditLine
# 1 = credit line changed from previous month, 0 = no change
df = df.sort_values(['BusinessID', 'MOB'])
df['Previous_DynamicCreditLine'] = df.groupby('BusinessID')['DynamicCreditLine'].shift(1)
df['AdjustCreditLine'] = (df['DynamicCreditLine'] != df['Previous_DynamicCreditLine']).astype(int)
df['AdjustCreditLine'] = df['AdjustCreditLine'].fillna(0)

# Define features and targets
target_binary     = 'AdjustCreditLine'
target_regression = 'DynamicCreditLine'
features = [col for col in df.columns if col not in [target_binary, target_regression,
                                                       'Previous_DynamicCreditLine', 'BusinessID']]
print("\nInitial Features:", features)

# Label encode Industry_Type
label_encoder_industry = LabelEncoder()
df['industry_code'] = label_encoder_industry.fit_transform(df['Industry_Type'])
features = [col for col in features if col != 'Industry_Type'] + ['industry_code']

categorical_cols = ['Loan_Purpose', 'Collateral_Type']
numerical_cols   = [col for col in features if col not in categorical_cols + ['industry_code']]

print("\nUpdated Features:", features)
print("Categorical Columns:", categorical_cols)
print("Numerical Columns:", numerical_cols)

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num',  StandardScaler(),                                   numerical_cols),
        ('cat',  OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols),
        ('pass', 'passthrough',                                      ['industry_code'])
    ],
    remainder='drop'
)

# Split data
X = df[features]
y_binary = df[target_binary]
X_train, X_temp, y_train_binary, y_temp_binary = train_test_split(X, y_binary, test_size=0.3, random_state=42)
X_val,   X_test, y_val_binary,   y_test_binary = train_test_split(X_temp, y_temp_binary, test_size=0.5, random_state=42)

# Train classification model
clf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier',   XGBClassifier(random_state=42, eval_metric='logloss'))
])
clf_pipeline.fit(X_train, y_train_binary)

# Evaluate on Validation Set
y_val_pred_binary = clf_pipeline.predict(X_val)
print("\nClassification Model Evaluation (Validation Set):")
print(classification_report(y_val_binary, y_val_pred_binary))
print(f"Accuracy: {accuracy_score(y_val_binary, y_val_pred_binary):.4f}")

# Evaluate on Test Set
y_test_pred_binary = clf_pipeline.predict(X_test)
print("\nClassification Model Evaluation (Test Set):")
print(classification_report(y_test_binary, y_test_pred_binary))
print(f"Accuracy: {accuracy_score(y_test_binary, y_test_pred_binary):.4f}")

# Save predictions
df['Predicted_AdjustCreditLine'] = clf_pipeline.predict(X)

"""Feature Importance (Classification)"""

# Get feature names after OneHotEncoding
ohe = clf_pipeline.named_steps['preprocessor'].named_transformers_['cat']
ohe_feature_names = ohe.get_feature_names_out(categorical_cols)
all_feature_names = np.concatenate([numerical_cols, ohe_feature_names, ['industry_code']])

# Build feature importance dataframe
clf_feature_importance_df = pd.DataFrame({
    'Feature':    all_feature_names,
    'Importance': clf_pipeline.named_steps['classifier'].feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=clf_feature_importance_df.head(10))
plt.title('Top 10 Feature Importance for Classification Model (AdjustCreditLine)')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""XGBoost Regression"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# Fix unstable Collateral_Type per BusinessID (set to mode value)
collateral_changes = df.groupby('BusinessID')['Collateral_Type'].nunique().reset_index()
collateral_changes.columns = ['BusinessID', 'Unique_Collateral_Values']
unstable_ids = collateral_changes[collateral_changes['Unique_Collateral_Values'] > 1]

print(f"\nNumber of BusinessIDs with unstable Collateral_Type: {len(unstable_ids)}")

df['Collateral_Type'] = df.groupby('BusinessID')['Collateral_Type'].transform(
    lambda x: x.mode()[0] if not x.mode().empty else x.iloc[0]
)
print("Data corrected: Collateral_Type set to mode value per BusinessID.")

# Filter only rows where credit line adjustment is predicted
df_regression = df[df['Predicted_AdjustCreditLine'] == 1].copy()
print(f"\nRegression dataset size: {len(df_regression)} rows")

# Split regression data
X_reg = df_regression[features]
y_reg = df_regression[target_regression]
X_train_reg, X_temp_reg, y_train_reg, y_temp_reg = train_test_split(X_reg, y_reg, test_size=0.3, random_state=42)
X_val_reg,   X_test_reg, y_val_reg,   y_test_reg = train_test_split(X_temp_reg, y_temp_reg, test_size=0.5, random_state=42)

# Train regression model
reg_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor',    XGBRegressor(random_state=42))
])
reg_pipeline.fit(X_train_reg, y_train_reg)

# Evaluate on Validation Set
y_val_pred_reg = reg_pipeline.predict(X_val_reg)
print("\nRegression Model Evaluation (Validation Set):")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_val_reg, y_val_pred_reg):.2f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mean_squared_error(y_val_reg, y_val_pred_reg)):.2f}")
print(f"R² Score: {r2_score(y_val_reg, y_val_pred_reg):.4f}")

# Evaluate on Test Set
y_test_pred_reg = reg_pipeline.predict(X_test_reg)
print("\nRegression Model Evaluation (Test Set):")
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_test_reg, y_test_pred_reg):.2f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mean_squared_error(y_test_reg, y_test_pred_reg)):.2f}")
print(f"R² Score: {r2_score(y_test_reg, y_test_pred_reg):.4f}")

"""Feature Importance (Regression) + Export Results"""

# Feature importance for regression model
reg_feature_importance_df = pd.DataFrame({
    'Feature':    all_feature_names,
    'Importance': reg_pipeline.named_steps['regressor'].feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=reg_feature_importance_df.head(10))
plt.title('Top 10 Feature Importance for Regression Model (DynamicCreditLine)')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# Merge regression predictions back to main dataframe
df_regression['Predicted_DynamicCreditLine'] = reg_pipeline.predict(X_reg)
df = df.merge(df_regression[['BusinessID', 'MOB', 'Predicted_DynamicCreditLine']],
              on=['BusinessID', 'MOB'], how='left')

# Analyze Collateral Type vs Adjustment Rate
collateral_analysis = df.groupby('Collateral_Type')['Predicted_AdjustCreditLine'].value_counts().unstack(fill_value=0)
collateral_analysis.columns = ['No Adjustment (0)', 'Adjustment (1)']
collateral_analysis['Total'] = collateral_analysis['No Adjustment (0)'] + collateral_analysis['Adjustment (1)']
collateral_analysis['Adjustment Rate (%)'] = (collateral_analysis['Adjustment (1)'] / collateral_analysis['Total']) * 100
collateral_analysis = collateral_analysis.sort_values(by='Adjustment Rate (%)', ascending=False)

print("\nAnalysis of Collateral_Type Impact on Predicted_AdjustCreditLine:")
print(collateral_analysis)

plt.figure(figsize=(10, 6))
sns.barplot(x='Adjustment Rate (%)', y=collateral_analysis.index, data=collateral_analysis)
plt.title('Adjustment Rate by Collateral Type')
plt.xlabel('Adjustment Rate (%)')
plt.ylabel('Collateral Type')
plt.tight_layout()
plt.show()

# Export final results to CSV
output_path = '/content/SMB_Dynamic_Credit_Line_Output.csv'
df.to_csv(output_path, index=False)
print(f"\nData exported successfully to {output_path}")

print("\nSample Results (First 10 Rows):")
print(df[['BusinessID', 'MOB', 'DynamicCreditLine', 'AdjustCreditLine',
          'Predicted_AdjustCreditLine', 'Predicted_DynamicCreditLine']].head(10))

from google.colab import drive
drive.mount('/content/drive')